# Generated by Django 5.0.2 on 2024-05-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(blank=True, choices=[('US', 'Estados Unidos'), ('BR', 'Brasil')], max_length=100, null=True)),
            ],
        ),
    ]
